server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: TRACE
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id:
            client-secret:
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: {yournamespace}/
